version: '3'
services:
  api:
    build: ./app
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASS: root
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: urlshortener
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: