version: '3.8'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - /mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
  api:
    image: 934556830376.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-api:latest
    environment:
      DB_HOST: mysql
      DB_USER: admin
      DB_PASS: root
      DB_NAME: urlshortener
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - app-network
  frontend:
    image: 934556830376.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-frontend:latest
    ports:
      - "80:80"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
