apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 934556830376.dkr.ecr.ap-south-1.amazonaws.com/url-shortener-api:latest  # From Terraform output
        ports:
          - containerPort: 5000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: DB_NAME
          value: urlshortener
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: url-shortener
spec:
  type: LoadBalancer  # Expose externally
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: api