apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 3.110.114.163:5000/url-shortener-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "mysql://user:userpassword@mysql:3306/url_shortener"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: url-shortener
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
