apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: url-shortener
type: Opaque
data:
  MYSQL_USER: YWRtaW4=  # base64 'admin'
  MYSQL_PASSWORD: cm9vdA==  # base64 'root'
  MYSQL_ROOT_PASSWORD: cm9vdA==
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: url-shortener
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: urlshortener
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: url-shortener
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None  # Headless
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mysql-data  # Mounted EBS on master
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0  # Matches StatefulSet
  namespace: url-shortener
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi